# Generated by Django 4.0.4 on 2022-06-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=200)),
                ('cpf_aluno', models.IntegerField(max_length=11)),
                ('end_aluno', models.CharField(max_length=200)),
                ('escola_aluno', models.CharField(max_length=200)),
                ('end_escola_aluno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=200)),
                ('cnpj', models.IntegerField(max_length=14)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.IntegerField(max_length=12)),
                ('responsavel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_resp', models.CharField(max_length=200)),
                ('cpf_resp', models.IntegerField(max_length=11)),
                ('end_resp', models.CharField(max_length=200)),
                ('tel_resp', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='transportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_transp', models.CharField(max_length=200)),
                ('cpf_transp', models.IntegerField(max_length=11)),
                ('end_transp', models.CharField(max_length=200)),
                ('tel_transp', models.IntegerField(max_length=11)),
                ('veiculo', models.CharField(max_length=200)),
                ('placa', models.CharField(max_length=7)),
                ('capacidade', models.IntegerField(max_length=10)),
                ('tempo_atua', models.IntegerField(max_length=5)),
                ('escola_atende', models.CharField(max_length=1000)),
            ],
        ),
    ]
