# Generated by Django 4.0.4 on 2022-06-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cpf_aluno',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='cpf_resp',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='tel_resp',
        ),
        migrations.RemoveField(
            model_name='transportador',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='transportador',
            name='cpf_transp',
        ),
        migrations.RemoveField(
            model_name='transportador',
            name='tel_transp',
        ),
        migrations.RemoveField(
            model_name='transportador',
            name='tempo_atua',
        ),
    ]
