# Generated by Django 4.0.4 on 2022-06-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_aluno_cpf_aluno_remove_escola_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='end_escola_aluno',
            new_name='end_escola',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='escola_aluno',
            new_name='escola',
        ),
    ]
